/* eslint-disable no-unused-vars */
import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Users, Plus, Edit, Trash2, Download, Search, Filter, X, User, QrCode, Briefcase, Sun, CheckCircle, XCircle } from 'lucide-react';
import toast, { Toaster } from 'react-hot-toast';
import axios from 'axios';
import { TableSkeleton } from './LoadingSpinner';
import { qrAPI } from '../api/endpoints';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const BASE_URL = API_URL.replace('/api', ''); // http://localhost:5000

const client = axios.create({
  baseURL: API_URL,
  headers: {
    'Content-Type': 'application/json'
  }
});

// Interceptor para agregar token
client.interceptors.request.use((config) => {
  const token = localStorage.getItem('token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

export default function PersonalPanel() {
  const [personal, setPersonal] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterJornada, setFilterJornada] = useState('');
  const [filterEstado, setFilterEstado] = useState('');
  const [filterCargo, setFilterCargo] = useState('');
  const [filterGradoGuia, setFilterGradoGuia] = useState('');
  const [filterCurso, setFilterCurso] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [showCursosModal, setShowCursosModal] = useState(false);
  const [selectedDocenteCursos, setSelectedDocenteCursos] = useState(null);
  const [editingPersonal, setEditingPersonal] = useState(null);
  const [formData, setFormData] = useState({
    carnet: '',
    nombres: '',
    apellidos: '',
    sexo: '',
    cargo: 'Docente',
    jornada: '',
    grado_guia: '',
    curso: ''
  });

  // Sistema híbrido de carnets
  const [carnetMode, setCarnetMode] = useState('auto');
  const [suggestedCarnet, setSuggestedCarnet] = useState('');
  const [carnetValidation, setCarnetValidation] = useState({ valid: true, error: null });

  // Estados para reasignación de carnet
  const [showReasignarModal, setShowReasignarModal] = useState(false);
  const [nuevoCarnet, setNuevoCarnet] = useState('');
  const [reasignandoCarnet, setReasignandoCarnet] = useState(false);

  // Estado para el input de curso (cuando se agregan mÃºltiples)
  const [cursoInput, setCursoInput] = useState('');
  const [cursosList, setCursosList] = useState([]);

  // Colores para las etiquetas de cursos
  const courseColors = [
    'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
    'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300',
    'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300',
    'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300',
    'bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-300',
    'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300',
    'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300',
    'bg-teal-100 text-teal-800 dark:bg-teal-900/30 dark:text-teal-300',
  ];

  const getCourseColor = (courseName) => {
    let hash = 0;
    for (let i = 0; i < courseName.length; i++) {
      hash = courseName.charCodeAt(i) + ((hash << 5) - hash);
    }
    const index = Math.abs(hash) % courseColors.length;
    return courseColors[index];
  };

  const handleAddCurso = (e) => {
    e?.preventDefault();
    if (cursoInput.trim()) {
      if (!cursosList.includes(cursoInput.trim())) {
        setCursosList([...cursosList, cursoInput.trim()]);
      }
      setCursoInput('');
    }
  };

  const handleRemoveCurso = (cursoToRemove) => {
    setCursosList(cursosList.filter(c => c !== cursoToRemove));
  };

  const [posiblesGrados, setPosiblesGrados] = useState([]);
  const [qrModalData, setQrModalData] = useState(null);

  // Función para detectar si un carnet fue autogenerado
  const isAutoGeneratedCarnet = (carnet) => {
    if (!carnet) return false;
    // Patrón: [PREFIJO]-YYYYNNN
    // Prefijos válidos: D, DIR, SDIR, SEC, OP, AUX
    const autoPattern = /^(D|DIR|SDIR|SEC|OP|AUX)-\d{7}$/;
    return autoPattern.test(carnet);
  };

  useEffect(() => {
    fetchPersonal();
    generarGrados();
  }, []);

  const fetchPersonal = async () => {
    setLoading(true);
    try {
      const response = await client.get('/docentes');
      console.log('👨‍🏫 Respuesta de personal:', response.data);
      setPersonal(response.data.personal || []);
    } catch (error) {
      console.error('Error fetching personal:', error);
      toast.error('Error al cargar personal: ' + (error.response?.data?.error || error.message));
    } finally {
      setLoading(false);
    }
  };

  const generarGrados = () => {
    const grados = [
      '1ro. Primaria', '2do. Primaria', '3ro. Primaria', '4to. Primaria', '5to. Primaria', '6to. Primaria',
      '1ro. Básico', '2do. Básico', '3ro. Básico',
      '4to. Diversificado', '5to. Diversificado', '6to. Diversificado'
    ];
    setPosiblesGrados(grados);
  };

  // Fetch next carnet preview based on cargo
  const fetchNextCarnet = async (cargo) => {
    try {
      const response = await axios.get(`${API_URL}/docentes/next-carnet?cargo=${cargo}`, {
        headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` }
      });
      setSuggestedCarnet(response.data.carnet);
      if (carnetMode === 'auto' && !editingPersonal) {
        setFormData(prev => ({ ...prev, carnet: response.data.carnet }));
      }
    } catch (error) {
      console.error('Error fetching next carnet:', error);
    }
  };

  // Validate manual carnet
  const validateManualCarnet = async (carnet) => {
    if (!carnet) {
      setCarnetValidation({ valid: true, error: null });
      return;
    }
    try {
      const response = await axios.post(`${API_URL}/docentes/validate-carnet`,
        { carnet, excludeId: editingPersonal?.id },
        { headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` } }
      );
      setCarnetValidation(response.data);
    } catch (error) {
      setCarnetValidation({ valid: false, error: 'Error validando carnet' });
    }
  };

  // Effect para cargar carnet sugerido cuando cambia el cargo o el modo
  useEffect(() => {
    if (showModal && !editingPersonal && formData.cargo && carnetMode === 'auto') {
      fetchNextCarnet(formData.cargo);
    }
  }, [showModal, formData.cargo, editingPersonal, carnetMode]);

  const handleReasignarCarnet = async () => {
    if (!nuevoCarnet.trim()) {
      toast.error('Ingresa un carnet válido');
      return;
    }

    if (!carnetValidation.valid) {
      toast.error('El carnet ingresado no es válido o ya existe');
      return;
    }

    const toastId = toast.loading('Reasignando carnet...');
    setReasignandoCarnet(true);

    try {
      // 1. Actualizar el carnet
      await client.put(`/docentes/${editingPersonal.id}`, { carnet: nuevoCarnet });
      
      // 2. Regenerar QR automáticamente
      try {
        await axios.post(
          `${API_URL}/docentes/${editingPersonal.id}/regenerar-qr`,
          {},
          { headers: { 'Authorization': `Bearer ${localStorage.getItem('token')}` } }
        );
        toast.success('Carnet reasignado y QR regenerado', { id: toastId });
      } catch (qrError) {
        console.warn('Error regenerando QR:', qrError);
        toast.success('Carnet reasignado (QR pendiente)', { id: toastId });
      }

      // 3. Actualizar el personal en edición
      setEditingPersonal({ ...editingPersonal, carnet: nuevoCarnet });
      setFormData({ ...formData, carnet: nuevoCarnet });
      
      // 4. Cerrar modal y recargar datos
      setShowReasignarModal(false);
      setNuevoCarnet('');
      setCarnetValidation({ valid: true, error: null });
      fetchPersonal();
    } catch (error) {
      console.error('Error reasignando carnet:', error);
      toast.error('Error: ' + (error.response?.data?.error || error.message), { id: toastId });
    } finally {
      setReasignandoCarnet(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const toastId = toast.loading(editingPersonal ? 'Actualizando...' : 'Guardando...');
    
    try {
      const dataToSend = new FormData();
      
      // Agregar carnetMode para el sistema híbrido (solo al crear)
      if (!editingPersonal) {
        dataToSend.append('carnetMode', carnetMode);
      }
      
      // Actualizar el campo curso en formData con la lista unida por comas
      const finalFormData = {
        ...formData,
        curso: cursosList.join(', ')
      };

      Object.entries(finalFormData).forEach(([key, value]) => {
        if (key !== 'preview' && key !== 'foto' && value !== '' && value !== null && value !== undefined) {
          // Solo agregar carnet si es modo manual o si estamos editando
          if (key === 'carnet' && !editingPersonal && carnetMode === 'auto') {
            return; // Skip carnet en modo auto
          }
          dataToSend.append(key, value);
        }
      });

      if (formData.foto) {
        dataToSend.append('foto', formData.foto);
      }
      
      const config = {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      };

      if (editingPersonal) {
        await client.put(`/docentes/${editingPersonal.id}`, dataToSend, config);
        toast.success('Personal actualizado', { id: toastId });
      } else {
        await client.post('/docentes', dataToSend, config);
        toast.success('Personal agregado', { id: toastId });
      }
      
      setShowModal(false);
      setEditingPersonal(null);
      setFormData({
        carnet: '',
        nombres: '',
        apellidos: '',
        sexo: '',
        cargo: 'Docente',
        jornada: '',
        grado_guia: '',
        curso: '',
        foto: null,
        preview: null
      });
      setCursosList([]);
      setCursoInput('');
      fetchPersonal();
    } catch (error) {
      toast.error('Error: ' + (error.response?.data?.error || error.message), { id: toastId });
    }
  };

  const handleEdit = (miembro) => {
    setEditingPersonal(miembro);
    setFormData({
      carnet: miembro.carnet,
      nombres: miembro.nombres,
      apellidos: miembro.apellidos,
      sexo: miembro.sexo || '',
      cargo: miembro.cargo || 'Docente',
      jornada: miembro.jornada || '',
      grado_guia: miembro.grado_guia || '',
      curso: miembro.curso || '',
      foto: null,
      preview: miembro.foto_path ? (miembro.foto_path.startsWith('http') ? miembro.foto_path : `${BASE_URL}/uploads/${miembro.foto_path}`) : null
    });
    
    // Detectar automáticamente si el carnet fue autogenerado
    const isAuto = isAutoGeneratedCarnet(miembro.carnet);
    setCarnetMode(isAuto ? 'auto' : 'manual');
    
    // Si es automático, establecer el carnet sugerido
    if (isAuto) {
      setSuggestedCarnet(miembro.carnet);
    }
    
    // Cargar la lista de cursos si existe
    if (miembro.curso) {
      setCursosList(miembro.curso.split(',').map(c => c.trim()));
    } else {
      setCursosList([]);
    }
    setShowModal(true);
  };

  const handleDelete = async (id, nombre) => {
    if (!confirm(`¿Eliminar a ${nombre}?`)) return;
    
    const toastId = toast.loading('Eliminando...');
    try {
      await client.delete(`/docentes/${id}`);
      toast.success('Personal eliminado', { id: toastId });
      fetchPersonal();
    } catch (error) {
      toast.error('Error: ' + (error.response?.data?.error || error.message), { id: toastId });
    }
  };

  const handleViewCursos = (miembro) => {
    if (!miembro.curso) return;
    setSelectedDocenteCursos({
      nombre: `${miembro.nombres} ${miembro.apellidos}`,
      cursos: miembro.curso.split(',').map(c => c.trim()).sort()
    });
    setShowCursosModal(true);
  };

  const handleViewQR = async (id) => {
    try {
      const response = await qrAPI.download(id);
      const blob = new Blob([response.data], { type: 'image/png' });
      const url = window.URL.createObjectURL(blob);
      setQrModalData(url);
    } catch (error) {
      toast.error('Error al ver QR: ' + error.message);
    }
  };

  const handleDownloadQRsMasivo = async () => {
    const toastId = toast.loading('Generando códigos QR...');
    try {
      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();
      
      const personalADescargar = filteredPersonal.filter(p => p.codigos_qr?.[0]);
      
      if (personalADescargar.length === 0) {
        toast.error('No hay códigos QR para descargar', { id: toastId });
        return;
      }
      
      for (const miembro of personalADescargar) {
        try {
          const response = await qrAPI.download(miembro.codigos_qr[0].id);
          zip.file(`qr-${miembro.carnet}.png`, response.data);
        } catch (error) {
          console.error(`Error descargando QR de ${miembro.carnet}:`, error);
        }
      }
      
      const content = await zip.generateAsync({ type: 'blob' });
      const url = window.URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = `qr-personal-todos.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      
      toast.success(`${personalADescargar.length} códigos QR descargados`, { id: toastId });
    } catch (error) {
      toast.error('Error al generar ZIP: ' + error.message, { id: toastId });
    }
  };

  const handleToggleEstado = async (id, estadoActual, nombre) => {
    const nuevoEstado = estadoActual === 'activo' ? 'inactivo' : 'activo';
    const toastId = toast.loading(`Cambiando estado a ${nuevoEstado}...`);
    
    try {
      await client.put(`/docentes/${id}`, { estado: nuevoEstado });
      toast.success(`${nombre} ahora está ${nuevoEstado}`, { id: toastId });
      fetchPersonal();
    } catch (error) {
      toast.error('Error: ' + (error.response?.data?.error || error.message), { id: toastId });
    }
  };

  const handleDownloadQR = async (id, nombre) => {
    const toastId = toast.loading('Generando código QR...');
    
    try {
      const response = await client.get(`/qr/${id}/png`, { responseType: 'blob' });
      const blob = new Blob([response.data], { type: 'image/png' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `qr-miembro-${nombre || id}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
      toast.success('Código QR descargado', { id: toastId });
    } catch (error) {
      console.error('Error downloading QR:', error);
      toast.error('Error descargando QR: ' + error.message, { id: toastId });
    }
  };

  // Filtrar personal
  const filteredPersonal = personal.filter((miembro) => {
    const matchSearch = 
      miembro.nombres.toLowerCase().includes(searchTerm.toLowerCase()) ||
      miembro.apellidos.toLowerCase().includes(searchTerm.toLowerCase()) ||
      miembro.carnet.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchJornada = !filterJornada || miembro.jornada === filterJornada;
    const matchEstado = !filterEstado || miembro.estado === filterEstado;
    const matchCargo = !filterCargo || miembro.cargo === filterCargo;
    const matchGradoGuia = !filterGradoGuia || miembro.grado_guia === filterGradoGuia;
    const matchCurso = !filterCurso || (miembro.curso && miembro.curso.split(',').map(c => c.trim()).includes(filterCurso));
    
    return matchSearch && matchJornada && matchEstado && matchCargo && matchGradoGuia && matchCurso;
  });

  const jornadasUnicas = [...new Set(personal.map(d => d.jornada).filter(Boolean))];
  const cargosUnicos = [...new Set(personal.map(d => d.cargo).filter(Boolean))].sort();
  const gradosGuiaUnicos = [...new Set(personal.map(d => d.grado_guia).filter(Boolean))].sort();
  // Extraer cursos únicos de todos los miembros
  const cursosUnicos = [...new Set(personal.flatMap(d => d.curso ? d.curso.split(',').map(c => c.trim()) : []).filter(Boolean))].sort();

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"
      >
        <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-gray-100 flex items-center gap-3">
          <Users className="text-success dark:text-success-light" size={32} />
          Personal
        </h2>
        <button
          onClick={() => {
            setEditingPersonal(null);
            setFormData({
              carnet: '',
              nombres: '',
              apellidos: '',
              sexo: '',
              categoria: 'Docente',
              jornada: ''
            });
            setShowModal(true);
          }}
          className="bg-success hover:bg-success-dark dark:bg-success-light dark:hover:bg-success text-white font-bold py-2.5 px-5 rounded-lg flex items-center justify-center gap-2 transition-colors shadow-lg hover:shadow-xl"
        >
          <Plus size={20} />
          <span className="hidden sm:inline">Nuevo miembro</span>
          <span className="sm:hidden">Nuevo</span>
        </button>
      </motion.div>

      {/* Filtros */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white dark:bg-gray-800 rounded-xl shadow-md dark:shadow-gray-900/50 p-4 border border-gray-200 dark:border-gray-700"
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6 gap-4">
          <div className="col-span-1 sm:col-span-2 lg:col-span-1">
            <label className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <Search size={16} />
              Buscar
            </label>
            <input
              type="text"
              placeholder="Nombre o carnet..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500"
            />
          </div>
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <Briefcase size={16} />
              Cargo
            </label>
            <select
              value={filterCargo}
              onChange={(e) => setFilterCargo(e.target.value)}
              className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-gray-100"
            >
              <option value="">Todos</option>
              {cargosUnicos.map((cargo) => (
                <option key={cargo} value={cargo}>{cargo}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <Users size={16} />
              Grado Guía
            </label>
            <select
              value={filterGradoGuia}
              onChange={(e) => setFilterGradoGuia(e.target.value)}
              className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-gray-100"
            >
              <option value="">Todos</option>
              {gradosGuiaUnicos.map((grado) => (
                <option key={grado} value={grado}>{grado}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <Briefcase size={16} />
              Curso
            </label>
            <select
              value={filterCurso}
              onChange={(e) => setFilterCurso(e.target.value)}
              className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-gray-100"
            >
              <option value="">Todos</option>
              {cursosUnicos.map((curso) => (
                <option key={curso} value={curso}>{curso}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <Sun size={16} />
              Jornada
            </label>
            <select
              value={filterJornada}
              onChange={(e) => setFilterJornada(e.target.value)}
              className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-gray-100"
            >
              <option value="">Todas</option>
              {jornadasUnicas.map((jornada) => (
                <option key={jornada} value={jornada}>
                  {jornada}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="flex items-center gap-2 text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <Filter size={16} />
              Estado
            </label>
            <select
              value={filterEstado}
              onChange={(e) => setFilterEstado(e.target.value)}
              className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary-500 focus:border-transparent text-gray-900 dark:text-gray-100"
            >
              <option value="">Todos</option>
              <option value="activo">Activo</option>
              <option value="inactivo">Inactivo</option>
            </select>
          </div>
          <div className="flex flex-col gap-2">
            <button
              onClick={handleDownloadQRsMasivo}
              className="flex items-center justify-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition font-medium"
              title="Descargar QRs filtrados en ZIP"
            >
              <Download size={18} />
              Descargar QRs
            </button>
            <div className="text-sm text-gray-600 dark:text-gray-400 font-medium text-center">
              {filteredPersonal.length} de {personal.length} miembro(s)
            </div>
          </div>
        </div>
      </motion.div>

      {/* Tabla de personal */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white dark:bg-gray-800 rounded-xl shadow-lg dark:shadow-gray-900/50 overflow-hidden border border-gray-200 dark:border-gray-700"
      >
        {loading ? (
          <TableSkeleton rows={5} columns={7} />
        ) : filteredPersonal.length === 0 ? (
          <div className="p-12 text-center text-gray-500 dark:text-gray-400">
            <User size={48} className="mx-auto mb-4 text-gray-300 dark:text-gray-600" />
            <p>No hay personal registrados</p>
          </div>
        ) : (
          <>
            {/* Desktop Table */}
            <div className="hidden lg:block overflow-x-auto">
              <table className="w-full">
                <thead className="bg-success dark:bg-success-dark text-white">
                  <tr>
                    <th className="px-4 py-4 text-center text-sm font-semibold w-16">No.</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Carnet</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Nombre Completo</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Cargo</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Grado Guía</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Curso</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Jornada</th>
                    <th className="px-6 py-4 text-center text-sm font-semibold">Estado</th>
                    <th className="px-6 py-4 text-center text-sm font-semibold">Acciones</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
                  {filteredPersonal.map((miembro, index) => (
                    <motion.tr
                      key={miembro.id}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.05 }}
                      className="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors"
                    >
                      <td className="px-4 py-4 text-center">
                        <span className="text-sm font-semibold text-gray-600 dark:text-gray-400">
                          {index + 1}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="font-mono text-sm font-semibold text-success dark:text-success-light">
                          {miembro.carnet}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full overflow-hidden bg-gray-200 dark:bg-gray-700 flex-shrink-0">
                            {miembro.foto_path ? (
                              <img 
                                src={miembro.foto_path.startsWith('http') ? miembro.foto_path : `${BASE_URL}/uploads/${miembro.foto_path}`}
                                alt={`${miembro.nombres} ${miembro.apellidos}`}
                                className="w-full h-full object-cover"
                              />
                            ) : (
                              <div className="w-full h-full flex items-center justify-center text-gray-400 dark:text-gray-500">
                                <User size={20} />
                              </div>
                            )}
                          </div>
                          <div className="font-medium text-gray-900 dark:text-gray-100">
                            {miembro.nombres} {miembro.apellidos}
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600 dark:text-gray-400">
                        {miembro.cargo || 'Sin cargo'}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600 dark:text-gray-400">
                        {miembro.grado_guia || '-'}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-600 dark:text-gray-400 max-w-xs">
                        {miembro.curso ? (
                          <button
                            onClick={() => handleViewCursos(miembro)}
                            className="text-blue-600 dark:text-blue-400 hover:underline font-medium flex items-center gap-1"
                          >
                            Ver {miembro.curso.split(',').length} cursos
                          </button>
                        ) : '-'}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <span className="font-medium text-gray-900 dark:text-gray-100">
                          {miembro.jornada || '-'}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-center">
                        <span className={`inline-flex px-3 py-1 text-xs font-semibold rounded-full ${
                          miembro.estado === 'activo'
                            ? 'bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300'
                            : 'bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300'
                        }`}>
                          {miembro.estado}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex justify-center gap-2">
                          <button
                            onClick={() => handleViewQR(miembro.codigos_qr?.[0]?.id)}
                            className="p-2 text-purple-600 hover:bg-purple-50 dark:hover:bg-purple-900/20 rounded-lg transition"
                            title="Ver QR"
                            disabled={!miembro.codigos_qr?.[0]}
                          >
                            <QrCode size={18} />
                          </button>
                          <button
                            onClick={() => handleToggleEstado(miembro.id, miembro.estado, `${miembro.nombres} ${miembro.apellidos}`)}
                            className={`p-2 rounded-lg transition ${
                              miembro.estado === 'activo'
                                ? 'text-orange-600 hover:bg-orange-50 dark:hover:bg-orange-900/20'
                                : 'text-green-600 hover:bg-green-50 dark:hover:bg-green-900/20'
                            }`}
                            title={miembro.estado === 'activo' ? 'Desactivar' : 'Activar'}
                          >
                            {miembro.estado === 'activo' ? <XCircle size={18} /> : <CheckCircle size={18} />}
                          </button>
                          <button
                            onClick={() => handleEdit(miembro)}
                            className="p-2 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition"
                            title="Editar"
                          >
                            <Edit size={18} />
                          </button>
                          <button
                            onClick={() => handleDelete(miembro.id, `${miembro.nombres} ${miembro.apellidos}`)}
                            className="p-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition"
                            title="Eliminar"
                          >
                            <Trash2 size={18} />
                          </button>
                        </div>
                      </td>
                    </motion.tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Mobile Cards */}
            <div className="lg:hidden divide-y divide-gray-200">
              {filteredPersonal.map((miembro, index) => (
                <motion.div
                  key={miembro.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className="p-4 hover:bg-gray-50"
                >
                  <div className="flex justify-between items-start mb-3">
                    <div className="flex items-center gap-3 flex-1">
                      <span className="text-sm font-bold text-gray-500 dark:text-gray-400">#{index + 1}</span>
                      <div className="w-12 h-12 rounded-full overflow-hidden bg-gray-200 dark:bg-gray-700 flex-shrink-0">
                        {miembro.foto_path ? (
                          <img 
                            src={miembro.foto_path.startsWith('http') ? miembro.foto_path : `${BASE_URL}/uploads/${miembro.foto_path}`}
                            alt={`${miembro.nombres} ${miembro.apellidos}`}
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <div className="w-full h-full flex items-center justify-center text-gray-400 dark:text-gray-500">
                            <User size={24} />
                          </div>
                        )}
                      </div>
                      <div>
                        <div className="font-bold text-gray-900 dark:text-gray-100">{miembro.nombres} {miembro.apellidos}</div>
                        <div className="text-sm text-success font-mono font-semibold">{miembro.carnet}</div>
                        <div className="text-xs text-gray-600 dark:text-gray-400 mt-1">{miembro.cargo || 'Sin cargo'}</div>
                      </div>
                    </div>
                    <span className={`px-2 py-1 text-xs font-semibold rounded-full ${
                      miembro.estado === 'activo' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                    }`}>
                      {miembro.estado}
                    </span>
                  </div>
                  {miembro.jornada && (
                    <div className="flex items-center gap-1 text-sm text-gray-900 font-medium mb-3">
                      <Sun size={14} />
                      {miembro.jornada}
                      {miembro.curso && (
                        <div className="flex flex-wrap gap-1 mt-1 ml-2">
                          {miembro.curso.split(',').map((c, i) => (
                            <span 
                              key={i} 
                              className={`inline-block px-2 py-0.5 rounded text-xs font-medium ${getCourseColor(c.trim())}`}
                            >
                              {c.trim()}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      onClick={() => handleViewQR(miembro.codigos_qr?.[0]?.id)}
                      className="bg-purple-600 hover:bg-purple-700 text-white text-sm py-2 px-3 rounded-lg flex items-center justify-center gap-2 transition"
                      disabled={!miembro.codigos_qr?.[0]}
                    >
                      <QrCode size={16} />
                      QR
                    </button>
                    <button
                      onClick={() => handleToggleEstado(miembro.id, miembro.estado, `${miembro.nombres} ${miembro.apellidos}`)}
                      className={`text-white text-sm py-2 px-3 rounded-lg flex items-center justify-center gap-2 transition ${
                        miembro.estado === 'activo'
                          ? 'bg-orange-600 hover:bg-orange-700'
                          : 'bg-green-600 hover:bg-green-700'
                      }`}
                    >
                      {miembro.estado === 'activo' ? <XCircle size={16} /> : <CheckCircle size={16} />}
                      {miembro.estado === 'activo' ? 'Inactivar' : 'Activar'}
                    </button>
                    <button
                      onClick={() => handleEdit(miembro)}
                      className="bg-blue-600 hover:bg-blue-700 text-white text-sm py-2 px-3 rounded-lg flex items-center justify-center gap-2 transition"
                    >
                      <Edit size={16} />
                      Editar
                    </button>
                    <button
                      onClick={() => handleDelete(miembro.id, `${miembro.nombres} ${miembro.apellidos}`)}
                      className="bg-red-600 hover:bg-red-700 text-white text-sm py-2 px-3 rounded-lg flex items-center justify-center gap-2 transition"
                    >
                      <Trash2 size={16} />
                      Eliminar
                    </button>
                  </div>
                </motion.div>
              ))}
            </div>
          </>
        )}
      </motion.div>

      {/* Modal */}
      {showModal && createPortal(
        <AnimatePresence>
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-[9999] p-4 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              className="bg-white dark:bg-gray-800 rounded-xl p-5 sm:p-6 max-w-lg w-full shadow-2xl my-8 border border-gray-200 dark:border-gray-700"
            >
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-2xl font-bold text-gray-800 dark:text-gray-100">
                  {editingPersonal ? 'Editar Personal' : 'Nuevo Personal'}
                </h3>
                <button
                  onClick={() => setShowModal(false)}
                  className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition"
                >
                  <X size={24} />
                </button>
              </div>
            <form onSubmit={handleSubmit} className="space-y-3">
              <div className="flex flex-col items-center mb-4">
                  <div className="relative w-24 h-24 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center overflow-hidden border-2 border-dashed border-gray-400 dark:border-gray-500 mb-2 hover:border-success dark:hover:border-success-light transition-colors">
                    {formData.preview ? (
                      <img src={formData.preview} alt="Preview" className="w-full h-full object-cover" />
                    ) : (
                      <User size={40} className="text-gray-400 dark:text-gray-500" />
                    )}
                    <input
                      type="file"
                      accept="image/*"
                      onChange={(e) => {
                        const file = e.target.files[0];
                        if (file) {
                          setFormData({
                            ...formData,
                            foto: file,
                            preview: URL.createObjectURL(file)
                          });
                        }
                      }}
                      className="absolute inset-0 opacity-0 cursor-pointer"
                    />
                  </div>
                  <span className="text-sm text-gray-500 dark:text-gray-400">Toca para subir foto</span>
              </div>

              {/* Modo de Carnet - Solo visible al crear */}
              {!editingPersonal && (
                <div className="col-span-2 mb-2">
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Modo de Carnet</label>
                  <div className="flex gap-4">
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        checked={carnetMode === 'auto'}
                        onChange={() => {
                          setCarnetMode('auto');
                          // Regenerar carnet automático basado en el cargo actual
                          if (formData.cargo) {
                            fetchNextCarnet(formData.cargo);
                          }
                          setCarnetValidation({ valid: true, error: null });
                        }}
                        className="w-4 h-4 text-success"
                      />
                      <span className="text-sm text-gray-700 dark:text-gray-300">Automático</span>
                    </label>
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        checked={carnetMode === 'manual'}
                        onChange={() => {
                          setCarnetMode('manual');
                          setFormData({ ...formData, carnet: '' });
                        }}
                        className="w-4 h-4 text-success"
                      />
                      <span className="text-sm text-gray-700 dark:text-gray-300">Manual</span>
                    </label>
                  </div>
                </div>
              )}

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Carnet *</label>
                  {editingPersonal ? (
                    // Modo edición: carnet bloqueado con botón de reasignación
                    <div className="space-y-2">
                      <div className="w-full bg-gray-100 dark:bg-gray-700 border-2 border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 flex items-center justify-between">
                        <span className="font-mono font-bold text-gray-700 dark:text-gray-300">{formData.carnet}</span>
                        <span className="text-xs text-gray-500 dark:text-gray-400">🔒 Bloqueado</span>
                      </div>
                      <button
                        type="button"
                        onClick={() => {
                          setNuevoCarnet(formData.carnet);
                          setShowReasignarModal(true);
                        }}
                        className="w-full bg-orange-600 hover:bg-orange-700 text-white text-sm py-2 px-3 rounded-lg flex items-center justify-center gap-2 transition font-medium"
                      >
                        ⚠️ Reasignar Carnet
                      </button>
                    </div>
                  ) : carnetMode === 'auto' ? (
                    // Modo creación automático
                    <div className="w-full bg-green-50 dark:bg-green-900/20 border-2 border-green-300 dark:border-green-700 rounded-lg px-4 py-2.5 flex items-center justify-between">
                      <span className="font-mono font-bold text-green-700 dark:text-green-300">{suggestedCarnet || 'Cargando...'}</span>
                      <span className="text-xs text-green-600 dark:text-green-400">Auto</span>
                    </div>
                  ) : (
                    // Modo creación manual
                    <div>
                      <input
                        type="text"
                        required
                        value={formData.carnet}
                        onChange={(e) => {
                          const value = e.target.value;
                          setFormData({ ...formData, carnet: value });
                          validateManualCarnet(value);
                        }}
                        className={`w-full bg-white dark:bg-gray-700 border rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500 ${
                          carnetValidation.valid ? 'border-gray-300 dark:border-gray-600' : 'border-red-500'
                        }`}
                        placeholder="D-2026001"
                      />
                      {!carnetValidation.valid && (
                        <p className="text-xs text-red-600 mt-1">{carnetValidation.error}</p>
                      )}
                      <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">Formato: [PREFIJO]-YYYYNNN</p>
                    </div>
                  )}
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Cargo *</label>
                  <select
                    required
                    value={formData.cargo}
                    onChange={(e) => setFormData({ ...formData, cargo: e.target.value })}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100"
                  >
                    <option value="">-</option>
                    <option value="Docente">Docente</option>
                    <option value="Director">Director</option>
                    <option value="Directora">Directora</option>
                    <option value="Director General">Director General</option>
                    <option value="Directora General">Directora General</option>
                    <option value="Director Técnico">Director Técnico</option>
                    <option value="Directora Técnica">Directora Técnica</option>
                    <option value="Subdirector">Subdirector</option>
                    <option value="Subdirectora">Subdirectora</option>
                    <option value="Secretaria">Secretaria</option>
                    <option value="Secretario">Secretario</option>
                    <option value="Operativo">Operativo</option>
                    <option value="Auxiliar">Auxiliar</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Nombres *</label>
                  <input
                    type="text"
                    required
                    value={formData.nombres}
                    onChange={(e) => setFormData({ ...formData, nombres: e.target.value })}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Apellidos *</label>
                  <input
                    type="text"
                    required
                    value={formData.apellidos}
                    onChange={(e) => setFormData({ ...formData, apellidos: e.target.value })}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Sexo</label>
                  <select
                    value={formData.sexo}
                    onChange={(e) => setFormData({ ...formData, sexo: e.target.value })}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100"
                  >
                    <option value="">-</option>
                    <option value="Masculino">Masculino</option>
                    <option value="Femenino">Femenino</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Jornada</label>
                  <select
                    value={formData.jornada}
                    onChange={(e) => setFormData({ ...formData, jornada: e.target.value })}
                    className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100"
                  >
                    <option value="">-</option>
                    <option value="Matutina">Matutina</option>
                    <option value="Vespertina">Vespertina</option>
                    <option value="Nocturna">Nocturna</option>
                    <option value="Semipresencial">Semipresencial</option>
                    <option value="Virtual">Virtual</option>
                    <option value="Fin de Semana (Sábado)">Fin de Semana (Sábado)</option>
                    <option value="Fin de Semana (Domingo)">Fin de Semana (Domingo)</option>
                    <option value="Extendida">Extendida</option>
                  </select>
                </div>
              </div>

              {/* Campo Docente Guía y Curso - solo visibles si cargo es Docente */}
              {formData.cargo === 'Docente' && (
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Docente Guía
                    </label>
                    <select
                      value={formData.grado_guia}
                      onChange={(e) => setFormData({ ...formData, grado_guia: e.target.value })}
                      className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100"
                    >
                      <option value="">-</option>
                      {posiblesGrados.map((g) => (
                        <option key={g} value={g}>{g}</option>
                      ))}
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                      Cursos
                    </label>
                    <div className="mb-2">
                        <input
                        type="text"
                        value={cursoInput}
                        onChange={(e) => setCursoInput(e.target.value)}
                        onKeyDown={(e) => {
                            if (e.key === 'Enter') {
                            e.preventDefault();
                            handleAddCurso();
                            }
                        }}
                        placeholder="Escribe y presiona Enter"
                        className="w-full bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-success focus:border-transparent text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500"
                        />
                    </div>
                    
                    {/* Lista de chips de cursos */}
                    <div className="flex flex-wrap gap-2 min-h-[30px] p-2 bg-gray-50 dark:bg-gray-800/50 rounded-lg border border-gray-100 dark:border-gray-700">
                        {cursosList.length === 0 && (
                        <span className="text-xs text-gray-400 italic">No hay cursos asignados</span>
                        )}
                        {cursosList.map((c, index) => (
                        <span 
                            key={index} 
                            className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-semibold ${getCourseColor(c)}`}
                        >
                            {c}
                            <button
                            type="button"
                            onClick={() => handleRemoveCurso(c)}
                            className="hover:text-red-500 focus:outline-none"
                            >
                            <X size={12} />
                            </button>
                        </span>
                        ))}
                    </div>
                  </div>
                </div>
              )}

              <div className="flex gap-3 pt-4">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="flex-1 bg-gray-300 hover:bg-gray-400 dark:bg-gray-600 dark:hover:bg-gray-500 text-gray-800 dark:text-gray-100 font-bold py-2.5 rounded-lg transition"
                >
                  Cancelar
                </button>
                <button
                  type="submit"
                  className="flex-1 bg-success hover:bg-success-dark dark:bg-success-light dark:hover:bg-success text-white font-bold py-2.5 rounded-lg transition"
                >
                  {editingPersonal ? 'Actualizar' : 'Crear'}
                </button>
              </div>
            </form>
            </motion.div>
          </div>
        </AnimatePresence>,
        document.body
      )}

    {/* Toast notifications */}
    <Toaster
      position="top-right"
      containerStyle={{
        zIndex: 99999
      }}
      toastOptions={{
        duration: 3000,
        style: {
          background: '#fff',
          color: '#363636',
          boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
        },
        success: {
          iconTheme: {
            primary: '#10b981',
            secondary: '#fff',
          },
        },
        error: {
          iconTheme: {
            primary: '#ef4444',
            secondary: '#fff',
          },
        },
      }}
    />

      {/* Modal de visualización de QR */}
      {qrModalData && createPortal(
        <div 
          className="fixed inset-0 bg-black/50 flex items-center justify-center z-[100000]"
          onClick={() => setQrModalData(null)}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white dark:bg-gray-800 rounded-lg p-6 max-w-md w-full mx-4"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Código QR</h3>
              <button
                onClick={() => setQrModalData(null)}
                className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition"
              >
                <X size={20} />
              </button>
            </div>
            <div className="flex justify-center">
              <img src={qrModalData} alt="Código QR" className="max-w-full h-auto" />
            </div>
          </motion.div>
        </div>,
        document.body
      )}
      {/* Modal de Cursos */}
      <AnimatePresence>
        {showCursosModal && selectedDocenteCursos && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl w-full max-w-md overflow-hidden"
            >
              <div className="p-6 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center bg-gray-50 dark:bg-gray-800/50">
                <div>
                  <h2 className="text-xl font-bold text-gray-900 dark:text-white">Cursos Impartidos</h2>
                  <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">{selectedDocenteCursos.nombre}</p>
                </div>
                <button
                  onClick={() => setShowCursosModal(false)}
                  className="text-gray-400 hover:text-gray-500 dark:hover:text-gray-300 transition-colors p-2 hover:bg-gray-100 dark:hover:bg-gray-700/50 rounded-full"
                >
                  <X size={20} />
                </button>
              </div>
              
              <div className="p-6 max-h-[60vh] overflow-y-auto">
                <div className="space-y-2">
                  {selectedDocenteCursos.cursos.map((curso, index) => (
                    <div 
                      key={index}
                      className="flex items-center gap-3 p-3 rounded-xl bg-gray-50 dark:bg-gray-700/30 border border-gray-100 dark:border-gray-700 hover:shadow-sm transition-all duration-200"
                    >
                      <span className="flex items-center justify-center w-8 h-8 rounded-full bg-white dark:bg-gray-800 text-sm font-bold text-gray-500 shadow-sm">
                        {index + 1}
                      </span>
                      <span className={`px-3 py-1 rounded-lg text-sm font-semibold flex-1 ${getCourseColor(curso)}`}>
                        {curso}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="p-6 pt-2">
                <button
                  onClick={() => setShowCursosModal(false)}
                  className="w-full bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 font-bold py-3 rounded-xl transition"
                >
                  Cerrar
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Modal de Reasignación de Carnet */}
      {showReasignarModal && createPortal(
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-[9999] p-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white dark:bg-gray-800 rounded-xl p-6 max-w-md w-full shadow-2xl border border-gray-200 dark:border-gray-700"
          >
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-xl font-bold text-gray-800 dark:text-gray-100 flex items-center gap-2">
                ⚠️ Reasignar Carnet
              </h3>
              <button
                onClick={() => {
                  setShowReasignarModal(false);
                  setNuevoCarnet('');
                  setCarnetValidation({ valid: true, error: null });
                }}
                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition"
              >
                <X size={24} />
              </button>
            </div>

            <div className="mb-4 p-3 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
              <p className="text-sm text-yellow-800 dark:text-yellow-200 font-medium">
                🚨 <strong>Advertencia:</strong> Reasignar el carnet actualizará todos los registros asociados y regenerará el código QR automáticamente.
              </p>
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Carnet Actual
              </label>
              <div className="w-full bg-gray-100 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-lg px-4 py-2.5">
                <span className="font-mono font-bold text-gray-600 dark:text-gray-400">{formData.carnet}</span>
              </div>
            </div>

            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Nuevo Carnet *
              </label>
              <input
                type="text"
                value={nuevoCarnet}
                onChange={(e) => {
                  const value = e.target.value;
                  setNuevoCarnet(value);
                  validateManualCarnet(value);
                }}
                className={`w-full bg-white dark:bg-gray-700 border rounded-lg px-4 py-2.5 focus:ring-2 focus:ring-orange-500 focus:border-transparent text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500 ${
                  carnetValidation.valid ? 'border-gray-300 dark:border-gray-600' : 'border-red-500'
                }`}
                placeholder="D-2026001"
                autoFocus
              />
              {!carnetValidation.valid && (
                <p className="text-xs text-red-600 mt-1 flex items-center gap-1">
                  ❌ {carnetValidation.error}
                </p>
              )}
              {carnetValidation.valid && nuevoCarnet && nuevoCarnet !== formData.carnet && (
                <p className="text-xs text-green-600 mt-1 flex items-center gap-1">
                  ✅ Carnet disponible
                </p>
              )}
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">Formato: [PREFIJO]-YYYYNNN</p>
            </div>

            <div className="flex gap-3">
              <button
                type="button"
                onClick={() => {
                  setShowReasignarModal(false);
                  setNuevoCarnet('');
                  setCarnetValidation({ valid: true, error: null });
                }}
                className="flex-1 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200 font-medium py-2.5 px-4 rounded-lg transition"
                disabled={reasignandoCarnet}
              >
                Cancelar
              </button>
              <button
                type="button"
                onClick={handleReasignarCarnet}
                disabled={reasignandoCarnet || !carnetValidation.valid || !nuevoCarnet || nuevoCarnet === formData.carnet}
                className="flex-1 bg-orange-600 hover:bg-orange-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white font-bold py-2.5 px-4 rounded-lg transition flex items-center justify-center gap-2"
              >
                {reasignandoCarnet ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Reasignando...
                  </>
                ) : (
                  <>
                    ✅ Confirmar Reasignación
                  </>
                )}
              </button>
            </div>
          </motion.div>
        </div>,
        document.body
      )}
    </div>
  );
}
